#
# Jekyll basic configurations
#

# Re-include theme example pages for development
exclude:        []

# Disalbe custom plugins (jekyll-last-modified-at) for better performance
plugins:
  - match_regex
  - replace_regex

#
# Almace Scaffolding settings
#

# Enable development mode
dev:            true

# Reset base to / for localhost development
baseurl:        ""

# CDN location for development
file:           //sparanoid.s3-website-us-east-1.amazonaws.com

# Force UTF-8 since local server doesn't send charset in their respond header
force_utf_8:    true
